Bit-Quill/valkey-glide

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
Features:
* use `String[]` instead of `String...` for custom command in transaction
* fix handling custom command response with route
=> Fix custom command cluter & transaction implementation.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ServerManagementBaseCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/ClusterTransactionTests.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
Features:
* `CONFIG GET` https://redis.io/commands/config-get/
* `CONFIG SET` https://redis.io/commands/config-set/
=> Add `CONFIG GET` and `CONFIG SET` commands.

java/integTest/build.gradle, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TestConfiguration.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
Issue: https://github.com/orgs/Bit-Quill/projects/4/views/2?itemId=55479660&sliceBy%5Bvalue%5D=Java+Milestone+IV&pane=issue
=> Java: Use 3rd party lib for version checking.

java/client/src/main/java/glide/api/models/configuration/RequestRoutingConfiguration.java, java/client/src/main/java/glide/managers/CommandManager.java, java/client/src/test/java/glide/managers/CommandManagerTest.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
Related Ticket: https://github.com/orgs/Bit-Quill/projects/4?pane=issue&itemId=55731552
=> Java: enable routing by node address.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StringCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
[`STRLEN`](https://redis.io/commands/strlen/)
=> Add `STRLEN` command.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
* [`TYPE`](https://redis.io/commands/type/) command
* Transaction IT rework to ease reading and debugging
=> Add `TYPE` command.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ConnectionManagementBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
[`ECHO`](https://redis.io/commands/echo/)
=> Add `ECHO` command.

java/integTest/src/test/java/glide/ConnectionTests.java, java/integTest/src/test/java/glide/ErrorHandlingTests.java, java/integTest/src/test/java/glide/SharedClientTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/cluster/ClusterClientTests.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/StandaloneClientTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
Note: `@Timeout` annotation uses seconds as a default unit
=> Update timeout handling in IT.

glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
* [`BLPOP`](https://redis.io/commands/blpop/)
* [`BRPOP`](https://redis.io/commands/brpop/)
* TODO: update changelog if needed
ref: https://github.com/aws/glide-for-redis/pull/1113
=> Add `BLPOP` and `BRPOP` commands.

.github/workflows/java.yml, CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HyperLogLogBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/pfadd/
=> Add `PFADD` command.

CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HyperLogLogBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/pfcount/
This PR depends on #166
=> Add `PFCOUNT` command.

CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HyperLogLogBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/pfmerge/
Depends on #167 which depends on #166
=> Add `PFMERGE` command.

CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/rpushx/
https://redis.io/commands/lpushx/
TBD update changelog or not
=> Add `RPUSHX` and `LPUSHX` commands.

CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/commands/hkeys/
=> Python: adds HKEYS command

glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StringCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/setrange/
=> Add `SETRANGE` command.

CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/LinsertOptions.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/linsert/
=> Add `LINSERT` command.

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
* [`RPUSHX`](https://redis.io/commands/rpushx/)
* [`LPUSHX`](https://redis.io/commands/lpushx/)
=> Python: add RPUSHX and LPUSHX commands

java/client/src/test/java/glide/api/models/TransactionTests.java
Type every time `ArgsArray.newBuilder().addArgs` is pretty annoying...
=> Refactor transaction UT.

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/sinter/
=> Add `SINTER` command.

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/smove/
=> Add `SMOVE` command.

glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/bzpopmax/
ref: #149 and #174
=> Add `BZPOPMAX` command.

java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java
Popped from #198
Ninor clean up in trasnaction implementation (without code changes)
No BL changes.
=> Java: misc fixes

java/build.gradle
As it is required by appsec review.
=> Bump spotless version.

java/build.gradle, java/client/build.gradle, java/integTest/build.gradle
As it is required by appsec review.
=> Bump `lombok` version.

java/build.gradle, java/client/build.gradle, java/integTest/build.gradle, java/integTest/src/test/java/glide/SharedClientTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java
https://github.com/junit-team/junit5/issues/2597
=> Bump junit and update tests due to a breaking change.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/sunionstore/
=> Java: Add `SUNIONSTORE` command.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/sinterstore/
#203 + #181 = ~<3~ #214
=> Add `SINTERSTORE` command.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StringBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/getrange/
=> Add `GETRANGE` command.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/sdiffstore/
ref #203
=> Add `SDIFFSTORE` command.

java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py
Follow up from https://github.com/aws/glide-for-redis/pull/1239#discussion_r1557959459
=> Update docs for `LPUSHX` and `RPUSHX`

.github/workflows/csharp.yml, .github/workflows/go.yml, .github/workflows/install-redis/action.yml, .github/workflows/install-shared-dependencies/action.yml, .github/workflows/java.yml, .github/workflows/node.yml, .github/workflows/python.yml
* Fix for https://github.com/aws/glide-for-redis/issues/781
Use shared GHA step to install redis.
* Activate amazon linux runs on our fork. How it works?
=> Fix redis installation on macos and amazonlinux

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/commands/smismember/
=> Add `SMISMEMBER` command.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/SetOptions.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
https://redis.io/docs/latest/commands/lastsave/
=> Add `LASTSAVE` command.

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/linsert/
=> Python: add LINSERT command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/zlexcount/
=> Python: add ZLEXCOUNT command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/zrangebylex/
=> Python: add ZREMRANGEBYLEX command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/TestUtilities.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
https://redis.io/docs/latest/commands/save/
=> Java: Add `SAVE` command.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/sdiff/
refer to zdiff, sinter and sdiffstore
=> Add `SDIFF` command.

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
ref https://github.com/aws/glide-for-redis/pull/1221
=> Python: Add `PFADD` command.

glide-core/src/client/value_conversion.rs
as it was requested in https://github.com/Bit-Quill/glide-for-redis/commit/c2d7b407b29bb1a2806772daa839273e7fbede6e#r141023377
=> Core: Update data convertion for `SMISMEMBER`

CHANGELOG.md, node/.prettierignore, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
ref https://github.com/Bit-Quill/glide-for-redis/pull/229/
=> Node: Add `PFADD` command.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
Issue #, if available:
N/A
https://redis.io/commands/object-freq/
=> Java: Add OBJECT FREQ command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
N/A
https://redis.io/commands/object-idletime/
=> Java: Implement OBJECT IDLETIME command

java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
Update IT for `CONFIG REWRITE` to handle both cases as it is done in node test:
https://github.com/Bit-Quill/glide-for-redis/blob/369aff5f747ee11103d9d1e942d8229ab644edf3/node/tests/SharedTests.ts#L308-L326
=> Java: Fix IT for `CONFIG REWRITE`.

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/renamenx/
=> Add `RENAMENX` command.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HashBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/hkeys/
Docs copied from pythno client
=> Add `HKEYS` command.

.github/workflows/build-node-wrapper/action.yml, .github/workflows/build-python-wrapper/action.yml, .github/workflows/csharp.yml, .github/workflows/go.yml, .github/workflows/install-shared-dependencies/action.yml, .github/workflows/java.yml, .github/workflows/node-create-package-file/action.yml, .github/workflows/node.yml, .github/workflows/npm-cd.yml, .github/workflows/pypi-cd.yml, .github/workflows/python.yml, .github/workflows/rust.yml
1. use `macos-12` instead of `macos-latest`
2. prepare to switch from `ubuntu-latest` to `ubunty-$ver`
3. rename few CIs for better understading their statuses
4. disable CD workflows on forks
=> Fix CI workflows.

node/src/BaseClient.ts, node/src/Transaction.ts
Complete doc update started in https://github.com/aws/glide-for-redis/pull/1227 according to https://github.com/aws/glide-for-redis/issues/1215
=> Update examples in docs.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
Copy-paste from https://github.com/aws/glide-for-redis/pull/1255
https://redis.io/docs/latest/commands/bzpopmin/
=> Java: Add `BZPOPMIN` command.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GeospatialIndicesBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
Issue #, if available:
- adding Geopos
- adding Geopos tests
- adding to ArrayTransformUtils
=> Java: Add command Geopos. (Geospatial Indices Command Group)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GeospatialIndicesBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
Issue #, if available:
- adding Geopos
- adding Geopos tests
- adding to ArrayTransformUtils
recreated from https://github.com/Bit-Quill/glide-for-redis/pull/261 to clean up branching issues, containing original commit history/conversations
=> Java: Add command Geopos

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GeospatialIndicesBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/geospatial/GeoUnit.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/examples/src/main/java/glide/examples/ExamplesApp.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
- adding Geodist
- adding Geodist unit tests
- adding Geodist transaction tests
=> JAVA: Add command GEODIST

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/BitmapBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/setbit/
=> Java: Add `SETBIT` command

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GeospatialIndicesBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add command GeoHash

CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
- redis docs: https://redis.io/docs/latest/commands/zintercard/
=> Python: add ZINTERCARD command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/smove/
=> Python: add SMOVE command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/function/FunctionLoadOptions.java, java/client/src/main/java/module-info.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
https://redis.io/docs/latest/commands/function-load/
=> Java: Add `FUNCTION LOAD` command.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/ScoreFilter.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
https://redis.io/docs/latest/commands/zmpop/
Copy-pasted from BZMPOP
=> Java: Add `ZMPOP` command.

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/sdiffstore/
=> Python: add SDIFFSTORE command

python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/setrange/
=> Added Python: SETRANGE command

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HashBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/hrandfield/
Inspired by https://github.com/aws/glide-for-redis/pull/1334 and https://github.com/aws/glide-for-redis/pull/1238
=> Java: Add `HRANDFIELD` command.

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/PopDirection.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
- interface & client implementation
- new map type conversion
- javadoc
-
=> Java: Adding command `LMPOP`

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/sinterstore/
=> Python: add SINTERSTORE command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/smismember/
=> Python: add SMISMEMBER command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HashBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/hstrlen/
=> Java: Add `HSTRLEN` command.

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
interface & client implementation
new map type conversion
keeping this internal for now since the workflows dont auto trigger for me in upstream, will move forward once `lmpop` gets merged and this gets rebased on top
=> Java: Add command `BLMPOP`

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/object-freq/
Implementation and tests based off of https://github.com/aws/glide-for-redis/pull/1327
=> Python: add OBJECT FREQ command

node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://redis.io/docs/latest/commands/renamenx/
=> Added Node: RENAMENX command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/object-refcount/
=> Python: add OBJECT REFCOUNT command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
Adds the [XDEL](https://valkey.io/commands/xdel/) command
=> Java: add `XDEL` command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/pfcount/
=> Python: add PFCOUNT command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/pfmerge/
=> Python: add PFMERGE command

node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://redis.io/docs/latest/commands/sinter/
=> Node: added SINTER command

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/stream/StreamRange.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/examples/src/main/java/glide/examples/ExamplesApp.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
[XRANGE cmd](https://redis.io/docs/latest/commands/xrange/)
=> Java: Add the XRANGE command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/xlen/
=> Python: add XLEN command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Adding command `SRandMember`

CHANGELOG.md, python/python/glide/async_commands/cluster_commands.py, python/python/glide/async_commands/standalone_commands.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/lastsave/
=> Python: add LASTSAVE command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
https://redis.io/docs/latest/commands/function-delete/
Depends on #277 which depends on #270
=> Java: Add `FUNCTION DELETE` command.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/spop/
=> Java: add SPOP command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/FlushMode.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
https://redis.io/docs/latest/commands/function-flush/
Depends on #277 which depends on #270
=> java: Add `FUNCTION FLUSH` command.

java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
https://redis.io/docs/latest/commands/dbsize/
=> Java: add DBSIZE command

node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://redis.io/docs/latest/commands/pfcount/
=> Node: added PFCOUNT command

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/models/GlideString.java, java/client/src/main/java/glide/managers/BaseCommandResponseResolver.java, java/client/src/main/java/glide/managers/CommandManager.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/integTest/src/test/java/glide/SharedClientTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/src/lib.rs
Alternate solution for changes from https://github.com/aws/glide-for-redis/pull/1526, https://github.com/aws/glide-for-redis/pull/1535, https://github.com/aws/glide-for-redis/pull/1537
=> Java: Handle binary strings from GLIDE

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://redis.io/docs/latest/commands/sunionstore/
=> Node: add SUNIONSTORE command

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
N/A
https://redis.io/docs/latest/commands/zintercard/
=> Node: add ZINTERCARD command

glide-core/src/client/value_conversion.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/stream/StreamGroupOptions.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://valkey.io/commands/xgroup-create/
https://valkey.io/commands/xgroup-destroy/
=> Java: Add the `XGROUP CREATE` and `XGROUP DESTROY` commands

node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClient.test.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts
https://redis.io/docs/latest/commands/object-idletime/
=> Node: add OBJECT IDLETIME command

python/python/glide/__init__.py, python/python/glide/async_commands/bitmap.py, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/bitcount/
=> Python: add BITCOUNT command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StringBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/GetExOptions.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/getex/
=> Java: implement GETEX

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java, java/client/src/main/java/glide/api/models/commands/function/FunctionRestorePolicy.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
https://redis.io/docs/latest/commands/function-dump/
https://redis.io/docs/latest/commands/function-restore/
TODO:
=> Java: Add `FUNCTION DUMP` and `FUNCTION RESTORE`.

python/python/glide/async_commands/cluster_commands.py, python/python/glide/async_commands/standalone_commands.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/lolwut/
=> Python: Add LOLWUT command

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/PubSubBaseCommands.java, java/client/src/main/java/glide/api/commands/PubSubClusterCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/ClusterTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/ClusterTransactionTests.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
Note: IT comes in the next PR
https://redis.io/docs/latest/commands/spublish/
=> Add `PUBLISH` and `SPUBLISH` commands.

python/python/glide/async_commands/cluster_commands.py, python/python/glide/async_commands/standalone_commands.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/flushdb/
=> Python: added FLUSHDB command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
Note: E2E tests for this command are trivial
=> Java: Adding command WAIT

java/DEVELOPER.md
Revises the `DEVELOPER.md` file, based on experience following the installation instructions, to reduce some potential for confusion and add additional troubleshooting information.
=> Java: Revises `DEVELOPER.md` file.

node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/lset/
=> Node: implement LSET
