.github/workflows/java.yml
java/client/build.gradle
java/integTest/build.gradle
java/integTest/src/test/java/glide/CommandTests.java
java/integTest/src/test/java/glide/ConnectionTests.java
java/integTest/src/test/java/glide/TestConfiguration.java
java/integTest/src/test/resources/junit-platform.properties
utils/cluster_manager.py

Based on #54/https://github.com/aws/glide-for-redis/pull/796
This starts redis in standalone mode on port 6380 in CI and a cluster on ports 7000-7006.
To connect to standalone use:
```java
var client =
RedisClient.CreateClient(
RedisClientConfiguration.builder()
.address(
NodeAddress.builder()
.port(TestConfiguration.STANDALONE_PORT)
.build())
.build())
.get(10, TimeUnit.SECONDS);
```
To connect to cluster use:
```java
var clusterClient =
ClusterClient.CreateClient(
RedisClusterClientConfiguration.builder()
.address(
NodeAddress.builder()
.port(TestConfiguration.CLUSTER_PORT)
.build())
.requestTimeout(3000)
.build())
.get(10, TimeUnit.SECONDS);
```
**NOTE** don't use `Future::get` without specifying a timeout, because it hangs IT/CI on an error!
Test can be started by
```
./gradlew …
```

Add IT framework

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/ClusterClient.java
java/client/src/main/java/glide/api/RedisClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/BaseCommands.java
java/client/src/main/java/glide/api/commands/ClusterBaseCommands.java
java/client/src/main/java/glide/api/models/ClusterValue.java
java/client/src/main/java/glide/api/models/configuration/Route.java
java/client/src/main/java/glide/managers/CommandManager.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/ClusterValueTests.java
java/client/src/test/java/glide/api/models/RouteBuilderTests.java
java/client/src/test/java/glide/managers/CommandManagerTest.java

Depends on:
Features:
1. Cluster client
2. Cliend API to execute commands
3. Added option to execute every commands with routing settings
4. Added data conversion step: basic client converts data to string, cluster client converts to `RedisValue`, which is union to a string and a map
Use case:
```java
var client =
ClusterClient.CreateClient(
RedisClusterClientConfiguration.builder()
.address(
NodeAddress.builder()
.host("cluster.redis.com")
.build())
.useTLS(true)
.build())
.get();
var cmdRes1 = client.getCommandManager().get("956231").get();
// cmdRes1 contains a multi object => cmdRes1.hasMultiData() == true
//   <node1> : <value on node1>
//   <node2> : <value on node2>
//   <node3> : <value on node3>
// trying the same request to route to a single node:
var cmdRes2 = …
```

Add cluster client, request routes configuration and support for bulk response

---

java/client/build.gradle
java/client/src/main/java/glide/connectors/handlers/CallbackDispatcher.java
java/client/src/main/java/glide/connectors/handlers/ChannelHandler.java
java/client/src/main/java/glide/managers/BaseCommandResponseResolver.java
java/client/src/main/java/glide/managers/CommandManager.java
java/client/src/main/java/glide/managers/ConnectionManager.java
java/client/src/test/java/glide/ExceptionHandlingTests.java
java/client/src/test/java/glide/api/RedisClientCreateTest.java
java/client/src/test/java/glide/managers/CommandManagerTest.java
java/client/src/test/java/glide/managers/ConnectionManagerTest.java

1. Move error handling to `CallbackDispatcher`
2. Handle case of incorrect callback ID with `ClosingError` (ref: #851)
3. Close channel on `ClosingError`
4. Tests

Java client: update error handling

---

java/build.gradle
java/integTest/src/test/java/glide/CommandTests.java
java/integTest/src/test/java/glide/ConnectionTests.java
java/integTest/src/test/java/glide/TestConfiguration.java

```
./gradlew spotlessApply
```
adds missing header automatically for all java files
Next step (next PR(s)):
- spotless for gradle files
- linter for rust for license header check
- license header check for all [source] files in CI

Configure spotless to check/add licence header

---

java/README.md
java/benchmarks/build.gradle
java/benchmarks/src/main/java/glide/benchmarks/BenchmarkingApp.java
java/benchmarks/src/main/java/glide/benchmarks/clients/glide/GlideAsyncClient.java
java/benchmarks/src/main/java/glide/benchmarks/clients/lettuce/LettuceAsyncClient.java
java/examples/build.gradle
java/examples/src/main/java/glide/examples/ExamplesApp.java
java/examples/src/main/java/glide/examples/clients/GlideClient.java
java/settings.gradle

Add the Glide async client to the BenchmarkApp for the `install_and_test` script. 
Add the ExamplesApp for manually testing custom commands. 
Glide async client doesn't have cluster-mode client linked (TODO). 
ExamplesApp runs only custom command (no transactions, no specific commands - TODO). 
To run benchmark app, run: 
```
./gradlew :benchmarks:run --args="-clients GLIDE -dataSize 100 -concurrentTasks 100 -clientCount 1"
```
To run examples app, run: 
```
./gradlew :examples:run
```

Java: Add ExamplesApp and Update benchmarkingApp to both have Java/Glide-for-redis client

---

java/client/src/main/java/glide/connectors/handlers/ChannelHandler.java
java/client/src/main/java/glide/connectors/handlers/ReadHandler.java
java/client/src/main/java/glide/connectors/resources/ThreadPoolResource.java
java/client/src/test/java/glide/connection/ConnectionWithGlideMockTests.java
java/client/src/test/java/glide/utils/RustCoreLibMockTestBase.java
java/client/src/test/java/glide/utils/RustCoreMock.java

Features:
1. Error handling on UDS write
2. Error handling on UDS read
3. Glide core mock
4. Test superclass with glide core mock
5. Tests for error handling
Missing:
1. Error handling on channel creation. Left TODO there. Requires significant rework of `ChannelHandler`.
2. IT. Can't be reproduced in IT unfortunately.

Add UDS read/write error handling and tests with glide core mock.

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
java/client/src/main/java/glide/api/commands/StringCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/ClusterTransactionTests.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TestUtilities.java

Adding the DEL() command (String command)
Example: 
```
// assuming key1 and key2 exist, while key "invalid" does not. 
Integer result = client.del(new String[] {"key1", "key2", "invalid"}).get();
assert result == 2;
```

Java: Add DEL command

---

.github/workflows/csharp-benchmark.yml
.github/workflows/csharp.yml
.github/workflows/test-benchmark/action.yml
benchmarks/csharp/Program.cs
benchmarks/csharp/csharp_benchmark.csproj
csharp/lib/glide.csproj

Features:
* CI for C# benchmarking (runs on demand only)
* Update for benchmarking to include 2 more 3rd party clients

C#: benchmark GLIDER vs other clients

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/SetCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/ClusterTransactionTests.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TestUtilities.java

Adds initial set commands: `sadd`, `srem`, `smembers`, and `scard`.
Examples:
```java
Long saddResult = client.sadd("key", "member1", "member2", "member3", "member4").get();
assert saddResult == 4;
Long sremResult = client.srem("key", "member3").get();
assert sremResult == 1;
Set<String> smembersResult = client.smembers("key").get();
assert smembersResult.equals(Set.of("member1", "member2", "member4"));
Long scardResult = client.scard("key").get();
assert scardResult == 3;
```

Java: Add SADD, SREM, SMEMBERS, and SCARD commands (Set Commands)

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/ClusterTransactionTests.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TestUtilities.java

Adding the UNLINK() command (Generic command).  Note, unlink() and del() are very similar commands. 
Example: 
```
// assuming key1 and key2 exist, while key "invalid" does not. 
Integer result = client.unlink(new String[] {"key1", "key2", "invalid"}).get();
assert result == 2;
```

Java: Add UNLINK() command

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/ServerManagementBaseCommands.java
java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java
java/client/src/main/java/glide/api/commands/ServerManagementCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/client/src/test/java/glide/api/models/ClusterTransactionTests.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TestUtilities.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java
java/integTest/src/test/java/glide/cluster/CommandTests.java
java/integTest/src/test/java/glide/standalone/CommandTests.java

Features:
* `CONFIG REWRITE` https://redis.io/commands/config-rewrite/
* `CONFIG RESETSTAT` https://redis.io/commands/config-resetstat/
* UT consolidation for standalone and cluster client
* no IT for `CONFIG REWRITE`, because redis in IT runs without config file

Add `CONFIG REWRITE` and `CONFIG RESETSTAT`.

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/RedisClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/ConnectionManagementBaseCommands.java
java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TestUtilities.java
java/integTest/src/test/java/glide/cluster/CommandTests.java

Features:
* `CLIENT ID` https://redis.io/commands/client-id/
* `CLIENT GETNAME` https://redis.io/commands/client-getname/

Add `CLIENT ID` and `CLIENT GETNAME` commands.

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/RedisClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java
java/client/src/main/java/glide/api/commands/ConnectionManagementCommands.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/cluster/CommandTests.java
java/integTest/src/test/java/glide/standalone/CommandTests.java

Move the `ping()` command out of baseclient and into the redisclient.  Javadocs updated appropriately and copied more from Python.

Java: Move ping() commands out of baseclient

---

.github/workflows/csharp.yml
.github/workflows/go.yml
.github/workflows/java.yml
.github/workflows/lint-ts.yml
.github/workflows/node.yml
.github/workflows/python.yml
.github/workflows/rust.yml

Restore CI concurrency removed in #991.
To avoid conflicts between different CI workflows, every group name contains the wrapper name.
The purpose of this to cancel CI for a branch if it got a new commits (so new CI started).
Docs:
https://docs.github.com/en/actions/learn-github-actions/contexts
https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow

Configure concurrency for all CI.

---

.github/workflows/csharp.yml
csharp/tests/Integration/GetAndSet.cs
csharp/tests/Integration/IntegrationTestBase.cs
csharp/tests/Unit/Placeholder.cs

Run tests (IT & UT)
```
cd <repo root>/csharp
dotnet test -- NUnit.WorkDirectory=$PWD
```
Tests with report:
```
dotnet test "-l:html;LogFileName=TestReport.html" --results-directory . -- NUnit.WorkDirectory=$PWD
```
The approach is the same as for java client IT.
`IntegrationTestBase` class provides API to get redis ports, redis version and start/stop new instance.

C#: Make IT to manage redis.

---

java/client/src/main/java/glide/connectors/handlers/CallbackDispatcher.java
java/client/src/main/java/glide/connectors/handlers/ChannelHandler.java
java/client/src/main/java/glide/managers/CommandManager.java
java/client/src/test/java/glide/connection/ConnectionWithGlideMockTests.java
java/client/src/test/java/glide/managers/CommandManagerTest.java
java/integTest/src/test/java/glide/cluster/ClientTests.java
java/integTest/src/test/java/glide/standalone/ClientTests.java

Replaced future cancellations (for noncomplete futures) with exceptional completion using a ClosingException upon channel closure, aligning with Python and Node clients.
Added a mechanism to return a future with a ClosingException for command submissions on already closed clients. Introduced checks to see if the client has been already closed to catch it before submitting new commands.

Refactor channel closure handling

---

benchmarks/install_and_test.sh
java/benchmarks/src/main/java/glide/benchmarks/utils/Benchmarking.java

See benchmarking results in: https://github.com/aws/glide-for-redis/issues/691#issuecomment-1980111310
replaces: https://github.com/aws/glide-for-redis/issues/691

Java: Update benchmarking to use CachedThreadPool 

---

.github/workflows/go.yml
go/Makefile

- remove workflow_dispatch
- increase build timeout since other branches are hitting the 20 minute limit
- set LD_LIBRARY_PATH on ubuntu to fix error seen on other branches where libglide_rs.so could not be found. Note that this problem does not occur on mac
- remove the test report from CI. On other branches, it was discovered that the command to build the test report could hide build errors when running the tests. The test report also did not allow for logging test outcomes to GH actions at the same time as creating the report.
- remove unnecessary `cargo build` for glide-core. glide-core is built automatically when we run `cargo build` for the wrapper FFI lib.rs, so it was being built twice
- improve lint output when committed files do not match the required format

Go: miscellaneous CI improvements

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java

Adds the [PTTL](https://redis.io/commands/pttl/) command to the java wrapper

Add PPTL() command

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java

Add [Persist](https://redis.io/commands/persist)() command
Python changes: https://github.com/aws/glide-for-redis/pull/1129
Node changes: https://github.com/aws/glide-for-redis/pull/1023

Java: Add persist() command

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java
java/client/src/main/java/glide/api/commands/ConnectionManagementCommands.java
java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
java/client/src/main/java/glide/api/commands/GenericClusterCommands.java
java/client/src/main/java/glide/api/commands/GenericCommands.java
java/client/src/main/java/glide/api/commands/HashBaseCommands.java
java/client/src/main/java/glide/api/commands/ListBaseCommands.java
java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java
java/client/src/main/java/glide/api/commands/ServerManagementCommands.java
java/client/src/main/java/glide/api/commands/SetBaseCommands.java
java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
java/client/src/main/java/glide/api/commands/StringCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/main/java/glide/api/models/ClusterValue.java
java/client/src/main/java/glide/api/models/Transaction.java
java/client/src/main/java/glide/api/models/commands/SetOptions.java

Edits to make javadocs more consistent, including: 
* Starting javadocs in the present tense
* Adding code tags around Java objects and Java types

Javadoc fixes.

---

java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/client/src/test/java/glide/connection/ConnectionWithGlideMockTests.java
java/client/src/test/java/glide/connectors/resources/ThreadPoolResourceAllocatorTest.java
java/client/src/test/java/glide/ffi/FfiTest.java
java/client/src/test/java/glide/managers/ConnectionManagerTest.java
java/client/src/test/java/glide/utils/RustCoreMock.java

Cleans up all warnings in the Java/Client test folder.

Clean up all warnings in Java client test

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java
java/client/src/main/java/glide/api/commands/ConnectionManagementCommands.java
java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
java/client/src/main/java/glide/api/commands/GenericClusterCommands.java
java/client/src/main/java/glide/api/commands/GenericCommands.java
java/client/src/main/java/glide/api/commands/HashBaseCommands.java
java/client/src/main/java/glide/api/commands/ListBaseCommands.java
java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java
java/client/src/main/java/glide/api/commands/ServerManagementCommands.java
java/client/src/main/java/glide/api/commands/SetBaseCommands.java
java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
java/client/src/main/java/glide/api/commands/StringBaseCommands.java
java/client/src/main/java/glide/api/models/commands/SetOptions.java

Resolve two comments left for https://github.com/aws/glide-for-redis/pull/1104

Groom interface docs and names.

---

java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/GenericClusterCommands.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java

The `exec()` command (with a transaction as input argument) for cluster-clients must be routed to a single node.  Multi-node routes are not supported.

Fix transaction handling for cluster client.

---

java/client/src/main/java/glide/api/RedisClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/managers/CommandManager.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/client/src/test/java/glide/managers/CommandManagerTest.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java
java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
java/integTest/src/test/java/glide/standalone/TransactionTests.java

* Group commands in transaction IT.
* Ease transaction IT updating and fixing.
* Rename keys and values used in transaction IT to ease debugging.
* Rename `CommandManager` transaction related methods.
* Add number of commands missed in transaction IT.

Update transaction handling and IT

---

glide-core/src/client/value_conversion.rs
glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/main/java/glide/api/models/commands/WeightAggregateOptions.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java

https://redis.io/docs/latest/commands/zunionstore/
Data Conversion Required:
For the call to zunion when the "WITHSCORES" flag is passed. It returns a 2D array of [[String, Double]]. This return type needs to be converted to a MapOfStringDouble like ZDiff and ZRange.

Java: Add `Zunion` command. (Sorted Set Group)

---

glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java

Issue #, if available:
N/A
https://redis.io/commands/object-encoding/
The encodings that are no longer supported are not tested. The quicklist encoding is not tested because the default value for list-max-listpack-size is 8Kb and changing this value to something more practical to test requires updating the redis.conf.

Java: Add OBJECT ENCODING command

---

glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
java/integTest/src/test/java/glide/standalone/TransactionTests.java

N/A
https://redis.io/commands/object-refcount/

Java: Implement OBJECT REFCOUNT command

---

CHANGELOG.md
glide-core/src/client/value_conversion.rs
glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

N/A
- Add `HRANDFIELD` command: https://redis.io/commands/hrandfield/
- Includes value conversion: 
- RESP2 returns a flat array of BulkString values, where even-positioned elements are keys and odd-positioned elements are values. RESP3 returns an array of array of BulkString values (in other words, a 2D-array where the inner arrays are key-value pairs). The value conversion converts the RESP2 responses to the RESP3 format.
- Note that the returned type is a List instead of a Dict because the response may contain duplicates if the user passes in a negative `count` argument

Python: add HRANDFIELD command

---

java/integTest/src/test/java/glide/standalone/TransactionTests.java

Shared commands (Node) has this test for both cluster and standalone.  
Adding test for completeness.

Java: Add "WATCH returns null" standalone IT test

---

CHANGELOG.md
python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

N/A
- Add `BLPOP` command: https://redis.io/commands/blpop/
- Add `BRPOP` command: https://redis.io/commands/brpop/
Note: depends on https://github.com/aws/glide-for-redis/pull/1239

Python: add BLPOP and BRPOP commands

---

java/client/build.gradle

This change allows the Java client to properly run on ARM Linux.

Java: Add Netty epoll transport for ARM Linux

---

java/README.md
java/client/build.gradle
java/client/src/main/java/glide/ffi/resolvers/NativeUtils.java
java/client/src/main/java/glide/ffi/resolvers/ScriptResolver.java
java/examples/build.gradle

This change publishes the Java glide client JAR to the local Maven repository. The built JAR file contains the Rust native lib code. This is not portable, so we will need to ensure that we build one JAR per supported platform.

Java: Publish JAR to local Maven repository

---

glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/BitmapBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/main/java/glide/api/models/commands/BitMapOptions.java
java/client/src/main/java/glide/api/models/commands/BitcountOptions.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java

Implement https://redis.io/docs/latest/commands/bitcount/ in the java client.

Java: Add command `BITCOUNT`

---

glide-core/benches/rotating_buffer_benchmark.rs
glide-core/src/protobuf/redis_request.proto
glide-core/src/rotating_buffer.rs
glide-core/src/socket_listener.rs
glide-core/tests/test_socket_listener.rs
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/main/java/glide/api/models/Transaction.java
java/client/src/main/java/glide/api/models/commands/SetOptions.java
java/client/src/main/java/glide/managers/CommandManager.java
java/client/src/test/java/glide/api/models/StandaloneTransactionTests.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/client/src/test/java/glide/managers/CommandManagerTest.java
node/src/BaseClient.ts
node/src/Commands.ts
node/src/Transaction.ts
node/tests/RedisClient.test.ts
python/python/glide/redis_client.py

Without that rename we can't add command `command` to proto. Surprise!

Rename `Command` to `SingleCommand` in proto.

---

CHANGELOG.md
python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

https://redis.io/docs/latest/commands/zdiff/
Note: depends on update to cluster_routing.rs in redis-rs

Python: add ZDIFF command

---

CHANGELOG.md
glide-core/src/client/value_conversion.rs
glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
python/python/glide/__init__.py
python/python/glide/async_commands/core.py
python/python/glide/async_commands/sorted_set.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

https://redis.io/docs/latest/commands/bzmpop/
Note: 
- contains the same .rs and .proto changes as https://github.com/aws/glide-for-redis/pull/1390
- depends on https://github.com/aws/glide-for-redis/pull/1319 (will need to refactor tests to use compare_maps once 1319 is merged)

Python: add BZMPOP command

---

java/client/src/main/java/glide/api/logging/Logger.java
java/client/src/main/java/glide/connectors/handlers/CallbackDispatcher.java
java/client/src/main/java/glide/connectors/handlers/ReadHandler.java
java/client/src/main/java/glide/ffi/resolvers/LoggerResolver.java
java/client/src/main/java/module-info.java
java/client/src/test/java/glide/connection/ConnectionWithGlideMockTests.java
java/integTest/src/test/java/glide/LoggerTests.java
java/src/lib.rs

The Logger implementation here is based on the Python client's implementation, with some relatively small Java/JNI specific changes.

Java: Add Logger

---

CHANGELOG.md
python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

https://redis.io/docs/latest/commands/sunionstore/

Python: add SUNIONSTORE command

---

CHANGELOG.md
glide-core/src/client/value_conversion.rs
python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

https://redis.io/docs/latest/commands/sdiff/

Python: add SDIFF command

---

java/integTest/src/test/java/glide/TestUtilities.java
java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
java/integTest/src/test/java/glide/standalone/TransactionTests.java

Add deep comparison for nested collections.
Standard `assertEquals` uses `equals` method co compare collection entries (map, lists, etc), which does not work when an entry stores an array.

Update transaction IT.

---

glide-core/src/client/mod.rs
glide-core/src/client/value_conversion.rs

Small clean up to avoid logging sensitive user info - requests and responses.
https://github.com/Bit-Quill/glide-for-redis/actions/runs/9134317535/job/25119609032?pr=288#step:7:385

Don't log sensitive user info in GLIDE code

---

glide-core/src/client/value_conversion.rs
glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/RedisClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java
java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/main/java/glide/api/models/commands/function/FunctionListOptions.java
java/client/src/main/java/glide/managers/ConnectionManager.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/TestUtilities.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java
java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
java/integTest/src/test/java/glide/cluster/CommandTests.java
java/integTest/src/test/java/glide/standalone/CommandTests.java
java/integTest/src/test/java/glide/standalone/TransactionTests.java

https://redis.io/docs/latest/commands/function-list/
Depends/based on #270 
TODOs:

Add `FUNCTION LIST` command.

---

CHANGELOG.md
python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

https://redis.io/docs/latest/commands/object-encoding/
Implementation and tests based on Java implementation:
https://github.com/aws/glide-for-redis/pull/1313

Python: add OBJECT ENCODING command

---

CHANGELOG.md
python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

https://redis.io/docs/latest/commands/object-idletime/

Python: add OBJECT IDLETIME command

---

glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/ListBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java

Add command LSET

---

java/client/src/main/java/glide/api/RedisClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java
java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java
java/integTest/src/test/java/glide/cluster/CommandTests.java
java/integTest/src/test/java/glide/standalone/CommandTests.java

**BEFORE**
```js
String functionLoad(String code);
String functionLoadReplace(String code);
```
**AFTER**
```js
String functionLoad(String code, bool replace);
```

Java: Update implementation for `FUNCTION LOAD`.

---

CHANGELOG.md
python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

https://redis.io/docs/latest/commands/renamenx/

Python: add RENAMENX command

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java

- Update `ZUNION`
- Change `String[] zunion(KeysOrWeightedKeys)` -> `String[] zunion(KeyArray)`
- Remove `String[] zunion(KeysOrWeightedKeys, Aggregate)`, because it is useless (`Aggregate` is noop)
- Update `ZINTER`
- Change `String[] zinter(KeysOrWeightedKeys)` -> `String[] zunion(KeyArray)`
- Remove `String[] zinter(KeysOrWeightedKeys, Aggregate)`, because it is useless (`Aggregate` is noop)
- Add `@since` to `ZINTER`, `ZUNION` and `ZDIFF`
- Update UT for `ZINTER`, `ZUNION`
- Update command IT `ZINTER`, `ZUNION` and `ZDIFF` to check version and match new signatures
- Update transaction IT the same manner

Java: Update `ZUNION` and `ZINTER` and tests.

---

glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/RedisClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsBaseCommands.java
java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java
java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/TestUtilities.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java
java/integTest/src/test/java/glide/cluster/CommandTests.java
java/integTest/src/test/java/glide/standalone/CommandTests.java

https://redis.io/docs/latest/commands/fcall/
**Some details**
common interface functions
```js
Object fcall(String function, String[] keys, String[] arguments);
```
standalone interface functions
```js
Object fcall(String function);
```
cluster interface functions
```js
Object fcall(String function);
Object fcall(String function, Route route);
Object fcall(String function, String[] arguments);
Object fcall(String function, String[] arguments, Route route);
```
**This results in**
standalone client functions
```js
Object fcall(String function);
Object fcall(String function, String[] keys, String[] arguments);
```
cluster client functions
```js
Object fcall(String function); // routed to a random node
Object fcall(String function, Route route); // routed according to the given route
Object …
```

Java: Add `FCALL` command.

---

node/src/BaseClient.ts
node/src/Commands.ts
node/src/Transaction.ts
node/tests/RedisClusterClient.test.ts
node/tests/SharedTests.ts

https://redis.io/docs/latest/commands/object-freq/

Node: added OBJECT FREQ command

---

node/src/BaseClient.ts
node/src/Transaction.ts
node/tests/RedisClient.test.ts
node/tests/RedisClusterClient.test.ts
node/tests/SharedTests.ts
node/tests/TestUtilities.ts

Javascript follows camel-case for its variable naming convention. This PR updates the object command functions to follow camel-case.

Node: change object command names to follow camel-case

---

glide-core/src/client/value_conversion.rs
glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/RedisClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java
java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/RedisClusterClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/TestUtilities.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java
java/integTest/src/test/java/glide/cluster/CommandTests.java
java/integTest/src/test/java/glide/standalone/CommandTests.java

Depends and based on #333 on #328
Note: IT is incomplete, because `FUNCTION KILL` tests don't work

Add `FUNCTION STATS` command.

---

java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/RedisClient.java
java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/TransactionsBaseCommands.java
java/client/src/main/java/glide/api/commands/TransactionsClusterCommands.java
java/client/src/main/java/glide/api/commands/TransactionsCommands.java

Comments in https://github.com/aws/glide-for-redis/pull/1539 weren't fully addressed. This PR makes `unwatch` consistent with other keyless commands where the apis are duplicated for cluster and standalone clients for documentation purposes.

Separated unwatch to have different docs for standalone

---

glide-core/src/client/value_conversion.rs
glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java

depends on https://github.com/aws/glide-for-redis/pull/1557

Java: Add commands `XGROUP CREATECONSUMER` and `XGROUP DELCONSUMER`

---

java/client/build.gradle
java/client/src/test/java/glide/ffi/FfiTest.java
java/src/errors.rs
java/src/ffi_test.rs
java/src/lib.rs

This change restructures the FFI layer for the Java client to allow panics to be caught. It also allows errors to be caught in a more flexible and ergonomic manner. The API could theoretically be simplified further, but it is currently not feasible due to `catch_unwind` needing to take ownership of the `JNIEnv` due to this issue: https://github.com/jni-rs/jni-rs/issues/432

Java: Handle panics and errors in the Java FFI layer

---

java/client/src/main/java/glide/api/RedisClusterClient.java
java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java

https://github.com/aws/glide-for-redis/pull/1593#discussion_r1643240553

Java: Fix routing for `FLUSHALL` and `FLUSHDB`.

---

CHANGELOG.md
glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
python/python/glide/__init__.py
python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

- `SET` and `GetEx` takes a similar set of expiry metric inputs with 1 difference, is there a better way than creating a new set of enum/option class for getex's version? Adding to SET's enum will cause undesired behavior but this feels like a lot of duplicated code
update: Will priotize consistency in the client's behavior and avoid doing refactoring to `SET` for now, point above is tracked with an internal ticket [here](https://github.com/orgs/Bit-Quill/projects/5/views/1?filterQuery=-status%3A%22NEEDS+GROOMING%22+&pane=issue&itemId=67911212).

Add Python cmd GetEX

---

glide-core/src/client/value_conversion.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/main/java/glide/api/models/commands/stream/StreamReadGroupOptions.java
java/client/src/main/java/glide/utils/ArrayTransformUtils.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java
java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java

Dependent on https://github.com/aws/glide-for-redis/pull/1599/
Adds the [XREADGROUP](https://valkey.io/commands/xreadgroup/) command to Java
TODO:

Java: Add the `XREADGROUP` command

---

glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
java/client/src/main/java/glide/api/models/commands/RestoreOptions.java
java/client/src/test/java/glide/api/ByteArrayArgumentMatcher.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/integTest/src/test/java/glide/SharedCommandTests.java

https://redis.io/docs/latest/commands/dump/
https://redis.io/docs/latest/commands/restore/

Java: Add DUMP and RESTORE commands

---

glide-core/src/protobuf/redis_request.proto
glide-core/src/request_type.rs
java/client/src/main/java/glide/api/BaseClient.java
java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
java/client/src/main/java/glide/api/models/BaseTransaction.java
java/client/src/main/java/glide/api/models/commands/stream/StreamPendingOptions.java
java/client/src/main/java/glide/api/models/commands/stream/StreamRange.java
java/client/src/test/java/glide/api/RedisClientTest.java
java/client/src/test/java/glide/api/models/TransactionTests.java
java/integTest/src/test/java/glide/SharedCommandTests.java
java/integTest/src/test/java/glide/TransactionTestUtilities.java

Add command [XPENDING](https://redis.io/docs/latest/commands/xpending/)

Java: Add XPENDING command

---

glide-core/src/client/standalone_client.rs
python/python/glide/async_commands/cluster_commands.py
python/python/glide/async_commands/standalone_commands.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

- also updates the redis-rs module to point to the latest commit in redis-rs/main

Python: add RANDOMKEY command

---

python/python/glide/async_commands/core.py
python/python/glide/async_commands/transaction.py
python/python/tests/test_async_client.py
python/python/tests/test_transaction.py

python: add LCS command

---

java/README.md

Had an issue with git. Had to duplicate the PR to this one. Will close the old one. 
https://github.com/Bit-Quill/glide-for-redis/pull/388

Java: new README.md

---

java/.gitignore

The VSCode [Extension Pack for Java](https://code.visualstudio.com/docs/java/java-testing) includes JUnit support that may automatically create various `bin` folders and `junit-platform.properties` files. Based on personal experience, these can be created soon after cloning the repo, resulting in mysterious uncommitted file. Since VSCode and the Extension Pack for Java are likely to be widely used, it seems simplest to simply ignore everything in the `bin/` folders that get created.

Java: Ignores VSCode-created `bin` directories

---

.github/workflows/rust.yml

Add missing GH token to avoid `rate exceeded` error for non authenticated requests
https://github.com/aws/glide-for-redis/actions/runs/9227667494/job/25390082670?pr=1460
```
Prepare all required actions
Getting action download info
Run ./.github/workflows/lint-rust
Run actions/checkout@v4
Syncing repository: aws/glide-for-redis
...
...
Run arduino/setup-protoc@v3
Error: Error: API rate limit exceeded for 20.161.76.225. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

Fix rust linter CI.

---

node/src/BaseClient.ts
node/src/Commands.ts
node/src/GlideClient.ts
node/src/GlideClusterClient.ts
node/src/Transaction.ts
node/tests/PubSub.test.ts

Add binary variant for the following commands:
- `PSubbscribe`
- `Subscribe`
- `SSubscribe`
- `Unsubscribe`
- `SUnsubscribe`
- `PUnsubscribe`
Add decoder option to PUBSUB's `createClient()`.
Note: to complete `PUBSUB` subscribe commands, I have to cherry-pick already merged main branch PR #2201.

Add binary variant to PUBSUB subscribe commands
